# vim: ft=ruby

platform :ios, '13.6'
use_frameworks!
use_modular_headers!

workspace 'TipJarViewController.xcworkspace'

target 'TipJarViewController_Example' do
  pod 'TipJarViewController', :path => '../'

  target 'TipJarViewController_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete('IPHONEOS_DEPLOYMENT_TARGET')
      config.build_settings.delete('TARGETED_DEVICE_FAMILY')
      config.build_settings.delete('SWIFT_VERSION')
      config.build_settings.delete('ARCHS')
    end
  end
end
