author: "Lionheart Software"
author_url: "https://lionheartsw.com"
github_url: "https://github.com/lionheart/TipJarViewController"
github_file_prefix: "https://github.com/lionheart/TipJarViewController/tree/2.1.0"
xcodebuild_arguments: ["-workspace", "Example/TipJarViewController.xcworkspace", "-scheme", "TipJarViewController"]
readme: "README.md"
copyright: "&copy; 2016-2017 Lionheart Software LLC"
theme: fullwidth
head: "<style type='text/css'>body { font-family: -apple-system !important; }</style>"
use_safe_filenames: true

