# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: objective-c

before_install:
- gem update --system
- gem install bundler:1.17.1
- bundle install
- bundle exec pod install --product-directory=Example --repo-update

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TipJarViewController.xcworkspace -scheme TipJarViewController-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
